title = """\
        Config file for virtual school backend, \
        this file contains only inner static confuguration parameters. \
        """

[crypt_password]
salt_len = 8  # from 0 to 16 bytes for blake2b

[jwt_token]
access_token_exp = 360  # lifetime in seconds
refresh_token_exp = 2592000  # 2592000 is 1 month
token_algorithm = "HS256"