title = """\
        Config file for virtual school backend, \
        this file contains only inner confuguration parameters. \
        For example admin credentials for dev enviroment. \
        """

